services:
  ollama:
    build:
      context: ./ollama/
      args:
        models: llama3.1
    networks:
      - app-network
    ports:
      - "11434:11434"  # Expose to host

  mentorgpt:
    build:
      context: ./
    networks:
      - app-network
    ports:
      - "8501:8501"
    depends_on:
      - ollama

networks:
  app-network:
    driver: bridge
  