[project]
name = "mentor-gpt"
version = "0.1.0"
description = "A collection of customGPTs for mentoring"
authors = [
    { name = "Nikola Sobadjiev", email = "you@example.com" }
]
dependencies = [
    "litellm",
    "streamlit"
]
requires-python = ">=3.12"
